### DISCUSSION TITLE
Kodėl gaunu BackendNotImplemented su XLSX backendu?

### DISCUSSION THREAD

**Discussion by sirex** [atviriduomenys/spinta#1187] [Q&A] [answered]
Manifest:

```
 d | r | b | m | property | type    | ref | source           | prepare           | level | access |
 test_dataset             |         |     |                  |                   |       |        |
   | spinta               | xlsx    |     | spinta/test.xlsx |                   |       |        |
   |   |   | Area         |         |     | Area             |                   |       | open   |
   |   |   |   | id       | integer |     | _id              |                   |       |        |
   |   |   |   | name     | string  |     | name             |                   |       |        |
   |   |   |   |          | enum    |     |                  | swap(nan, 'NULL') |       |        |
   |   |   |   |          |         |     |                  | swap('', '---')   |       |        |
   |   |   |   |          |         |     |                  | ""---""           |       |        |
   |   |   |   |          |         |     |                  | NULL              |       |        |
   |   |   |   |          |         |     | test             | ""---""           |       |        |
   |   |   |   |          |         |     |                  | nan               |       |        |
 ```

Config:

```yaml
env: production
data_path: $PWD/$BASEDIR
default_auth_client: default

keymaps:
  default:
    type: sqlalchemy
    dsn: sqlite:///$PWD/$BASEDIR/keymap.db

backends:
  postgresql:
    type: postgresql
    dsn: postgresql://admin:admin123@localhost:54321/spinta
  csv:
    type: csv
    dsn: /
  default:
    type: xlsx
    dsn: /

manifest: default
manifests:
  default:
    type: csv
    path: manifest.csv
    backend: default
    keymap: default
    mode: internal

accesslog:
  type: file
  file: $PWD/$BASEDIR/accesslog.json
```

Error:

```python
spinta.datasets.backends.notimpl.components.BackendNotImplemented(name='default')
```

Nelabai suprantu kodel check/copy praeina gerai, o paleidimo metu jau blogai. Juk logika paleidimu metu ta pati kaip ir checko metu? Ar mano yaml blogas?  Remiausi šituo - https://ivpk.github.io/dsa/1.0/saltiniai.html#xlsx, bet nelabai randu pavyzdį configo su xlsx šaltiniu. 
 
Bendrai nelabai aišku kaip gali buti backend, bet buti ne implemented
