### DISCUSSION TITLE
SQL šaltinio adresas DSA faile

### DISCUSSION THREAD

**Discussion by varzgalys** [atviriduomenys/spinta#1221] [Q&A] [answered]
Dokumentacijoje (https://ivpk.github.io/dsa/draft/dimensijos.html#resource.ref) yra aprašyta situacija, kai nenorime nurodyti pilno duombazes adreso su prisijungimais pačiame DSA, kadangi ta patį adresą turim jau po config.yml. Tačiau dokumentacijoje nėra pavyzdžio kaip nurodyti į config.yml esančia reikšme. Bandyta palikti tuščia source, 'default', 'sql', tačiau visi variantai meta klaidas.

Pvz turim toki config.yml:

```yaml
env: test
data_path: $PWD/$BASEDIR
default_auth_client: default

keymaps:
  default:
    type: sqlalchemy
    dsn: sqlite:///$PWD/$BASEDIR/keymap.db

backends:
  default:
    type: postgresql
    dsn: postgresql://admin:admin123@localhost:54321/spinta

manifest: default
manifests:
  default:
    type: csv
    path: $PWD/$BASEDIR/manifest.csv
    backend: default
    keymap: default
    mode: external

accesslog:
  type: file
  file: $PWD/$BASEDIR/accesslog.json
```

ir toki DSA:
```
+----+--------------+----------+------+-------+----------+---------+-----+--------+---------+-------+--------+
| id | dataset      | resource | base | model | property | type    | ref | source | prepare | level | access |
+----+--------------+----------+------+-------+----------+---------+-----+--------+---------+-------+--------+
|    | test_dataset |          |      |       |          |         |     |        |         |       |        |
|    |              | spinta   |      |       |          | sql     |     |default |         |       |        |
|    |              |          |      |       |          |         |     |        |         |       |        |
|    |              |          |      | Area  |          |         | id  | area   |         |       | open   |
|    |              |          |      |       | id       | integer |     | id     |         |       |        |
|    |              |          |      |       | name     | string  |     | name   |         |       |        |
|    |              |          |      |       |          | enum    |     |        |         |       |        |
|    |              |          |      |       |          |         |     | '1'    | '2'     |       |        |
|    |              |          |      |       |          |         |     | '2'    | '2'     |       |        |
+----+--------------+----------+------+-------+----------+---------+-----+--------+---------+-------+--------+
```

Klaida:

```yaml
spinta.exceptions.BackendNotFound: Can't find backend 'default'.
  Context:
    component: spinta.datasets.components.Resource
    manifest: default
    dataset: test_dataset
    resource: spinta
    name: default
```
