### DISCUSSION TITLE
Kur (ar?) confige saugomas kelias iki DSA?

### DISCUSSION THREAD

**Discussion by karina-klinkeviciute** [atviriduomenys/spinta#1223] [Q&A] [answered]
Kai spinta paleista server mode, ir servina duomenis, kaip suprantu, ji vadovaujasi DSA, kad žinot, kokius duomenis gali teikti?

Jei taip, tai kur spintos konfigūracijoj yra saugomas kelias iki šių DSA, arba, tiksliau, kaip/ar jį galima gauti, pavyzdžiui, paleidus `upgrade` scriptą?

**Comment by varzgalys** [comment]
Nesu tikras kad tesingai suprantu, bet kiek žinau DSA būna nurodomas `config.yml` faile:

```
manifest: default
manifests:
  default:
    type: csv
    path: dsa.csv  # <-- DSA
    backend: default
    keymap: default
    mode: external
```
