### DISCUSSION TITLE
Python versijos `spinta` testams

### DISCUSSION THREAD

**Discussion by karina-klinkeviciute** [atviriduomenys/spinta#1329] [Q&A] [answered]
Gal vertėtų `spinta` testus githube leisti su visomis palaikomomis ar bent keliomis skirtingomis Python versijomis? Dabar, jei kažkoks dalykas deprecatintas 3.10+ versijose, ir dėl to kyla klaidos leidžiant `spinta`, testai to nepagauna.

**Comment by sirex** [comment, marked as answer]
Manau tikrai reikėtu, nes jau turime kelias klaidas, nes to nedarome:

- https://github.com/atviriduomenys/spinta/issues/986
- https://github.com/atviriduomenys/spinta/issues/1326

**Comment by riteris13** [comment]
Kurios versijos turėtų būti testuojamos? Kelias versijas atgal mes norime palaikyti? Ir ar reikia nuolatinio atnaujinimo su Python atnaujinimais? Kaip dažnai turi būti tikrinimas forward compliance?

**Reply by karina-klinkeviciute** [reply]
Tai manau, kad turėtų būti testuojamos visos palaikomos versijos, t.y. šiuo metu 3.9, 3.10, 3.11, 3.12, 3.13

Paties PSF palaikomų Python versijų sąrašas yra čia: https://devguide.python.org/versions/ 

Kai išeis nauja Python versija, irgi turėtų būti pridedama, o nebepalaikomos Python versijos turėtų būti išimamos, tai dokumentuojant. 

Tai turėtų būti įdėta į github CI workflow, ir šie testai turėtų būti leidžiami kiekvieną kartą, kai kuriamas naujas PR, kaip ir dabar. 

Problema turbūt ta, kad tai užtruks kelis kartus ilgiau. Jau dabar užtrunka kelias minutes, kol visi testai praeina, tada užtruktų apie pusvalandį. Bet gal nieko tokio tai?

**Reply by sirex** [reply]
Sutinku, kad turėtume palaikyti visas Python palaikomas versijas iš https://devguide.python.org/versions/.

Dėl testų greičio, gal GitHub CI leidžia testus skirtingoms versijoms leisti lygiagrečiai?

**Reply by karina-klinkeviciute** [reply]
Taip, pasidomėjau, tai galima leisti naudojant `matrix builds`, pavyzdys:

```yaml
name: Test on multiple Python versions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
```
