### ISSUE TITLE
Backend assignment process

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#1152]
Currently backend assignment is described in code as follows:

https://github.com/atviriduomenys/spinta/blob/a0c084b7f03ebc8159fb806a412622a7ad9ca2ba/spinta/types/model.py#L181-L196

For example if we have following manifest table:

    d | r | b | m | property | type    | ref      | source
    example                  |         |          |
      | resource1            | sql     | backend1 |
                             |         |          |
      |   |   | City         |         | id       | LANGUAGES
      |   |   |   | id       | integer |          | ID
      |   |   |   | name@lt  | string  |          | NAME

And accompanying configuration file:

```yaml
backends:
  default:
    type: postgresql
    dsn: postgresql://...
  backend1:
    type: sql
    dsn: sqlite://..

manifest: default
manifests:
  default:
    type: csv
    path: manifest.csv
    backend: default
    mode: internal
```

Backend can be assigned in following ways:

### Direct assignment

Backend can be assigned to a model directly as described here:

- https://github.com/atviriduomenys/spinta/issues/599

### External mode

If spinta is run with `--mode=external`, then only backend defined in manifest table is considered.

Then only `backend1` will be used, as specified in manifest table, because external model is used.

### Internal model

If spinta is run with `--mode=internal`, then backend specified in manifest table is ignored and only backend specified in manifest configuration is used. Unless backend is explicitly specified on model.

In the example a `default` backend will be used.

If spinta will be run without explicit `--mode` argument, then by default, mode assigned to manifest will be used, which in this case is `internal`.
