### ISSUE TITLE
WSDL/SOAP skaitymas su autentifikacija

### ISSUE THREAD

**Issue by martynasracct** [atviriduomenys/spinta#1275]
### Platesnis viso autentifikacijos proceso aprašymas

Atitinka "**P.1.60 - Kliento registravimas agnete**" žingsnį, aprašytą [Proceso diagramoje](https://github.com/atviriduomenys/dvms/blob/b21dda071449ce733f2851cdde5ba94555f91a03/drafts/bpmn/Processes.drawio.svg), "**P1 - Duomenų keitimosi susitarimo procesas**" procese.

![Image](https://github.com/user-attachments/assets/9228e21c-24ee-449f-a50b-7e8ef10cb2e8)

Pagal ilustraciją:
1. (Data Catalog dalis) Kataloge duomenų naudotojas (Data User) išsirenka reikiamus duomenų rinkinius sudaro sutartį, nurodydamas reikiamus `scope`: kuria "panaudojimo atvejį" (kitaip, elektroninė paslaugas), kuriai reikia duomenų. Tokiu būdu nurodoma, kokių duomenų rinkinių reikia iš skirtingų tiekėjų.
2. (Data Catalog dalis) Kataloge duomenų naudotojas prašo leidimų (funkcija "Prašyti leidimų", kitaip "Inicijuoti sutartį"). Kiekvienai institucijai automatiškai sugeneruojama sutartis.
3. (Data Catalog dalis) Institucijos patvirtina sutartis ir sukuria "Raktus" / "Klientus", kurius naudos naudotojas (Data User).
4. (Data Catalog dalis) Po sutarties parvirtinimo, katalogas automatiškai autorizacijos serveryje užregistruoja klientus ("Raktus") (naudos Gravitee API) ir duomenų naudotojui parodo UDTS credentials `client_id` ir `secret`.
6. (Data Agent dalis) Duomenų naudotojas naudojant UDTS credentials, kreipiasi į konkretų įmonės agentą (Data Agent) ir registruoja duomenų serviso klientą su jų autentifikacijos duomenimis (pvz registro centro `CallerCode`, `EndUserInfo` ir pan.). Tokiu būdu duomenų naudotojo `client_id` yra surišamas duomenų agento autentifikacijos duomenimis.
7. (Data Agent dalis) Kiekvieną kartą jungiantis, duomenų naudotojui užtenka nurodyti UDTS credentials, nes pagal `client_id` iš įmonės duomenų agente galima pasiimti duomenų serviso autentifikacijos duomenis, o iš autentifikacijos serviso - `scopes` ir kitus duomenis patvirtinti, kad prisijungimas yra galimas.
8. (Data Agent dalis) Aprašytame DSA `creds` funkcija paims institucijos duomenų agente išsaugotus autentifikacijos duomenis ir su jais kreipsis į duomenų servisą.

### Šitos užduoties metu įgyvendinti:

- Papildyti Spinta endpoint'us`auth_clients_add()` ir `auth_clients_patch_specific()` galimybe nurodyti papildomus autentifikacijos duomenis, kurie bus saugomi kartu su kliento duomenimis
- Įgyvendinti DSA `creds(key)` funkciją, kuri iš išsaugotų autentifikacijos duomenų, pagal nurodytą `key` grąžintų reikšmę
    - Funkcija dažniausiai bus naudojama taip: `creds("key").input("default")`

### `auth_clients_*` endpointų papildymas

`.yml` faile turi būti pridėtas naujas dictionary tipo atributas `backends`, kuriame bus saugomi papildomi autentifikacijos duomenys. `backends` dictionary raktai - resurso pavadinimai (tuo atveju, jei būtų keli duomenų šaltiniai, kuriem reikia skirtingų autentifikacijos duomenų), o reikšmė - dictionary su reikalingais autentifikacijos duomenimis (žiūrėti pavyzdžius)

`POST http://127.0.0.1:8000/auth/clients`

Request body:
```json
{
    "client_name": "Client Name 2",
    "secret": "6543e3rgf3436542ref",
    "backends": {
        "default": {
            "EndUserInfo": "some info",
            "Signature": "4t4fs34",
            "CallerSignature": "654rfni5t"
        }
    }
}
```

Užklausos metu sukurtas `.yml` failas:
```yml
client_id: 46d02980-01f8-46f7-badb-b8877234ea3d
client_name: Client Name 2
client_secret_hash: ghjrp4354gopwgpow53t
scopes: []
backends:                          # hardcoded reikšmė, kurioje bus saugomi autentifikacijos duomenys
    default:                       # Resource pavadinimas, kad būtų galima atskirti, kuriam resursui papildomi autentifikacijos duomenys naudojami
        EndUserInfo: some info     # Autentifikacijos duomenys
        Signature: 4t4fs34
        CallerSignature: 654rfni5t
```

`PATCH http://127.0.0.1:8000/auth/clients/{client}`

Request body:
```json
{
    "backends": {
        "default": {
            "EndUserInfo": "some new info",
            "Signature": "new_4t4fs34"
        }
    }
}
```

Užklausos metu atnaujintas `.yml` failas:
```yml
client_id: 46d02980-01f8-46f7-badb-b8877234ea3d
client_name: Client Name 2
client_secret_hash: ghjrp4354gopwgpow53t
scopes: []
backends: 
    default:
        EndUserInfo: some new info
        Signature: new_4t4fs34
```

### `creds(...)` funkcijos įgyvendinimas

`.yml` failas:
```yml
client_id: 46d02980-01f8-46f7-badb-b8877234ea3d
client_name: Client Name 2
client_secret_hash: ghjrp4354gopwgpow53t
scopes: []
backends: 
    default:
        caller: some info
        user: some more info
        signature: 4t4fs34
        caller_signature: 654rfni5t
```

### DSA:
```
dataset | resource | base | model              | property               | type     | ref              | source                                              | prepare                              
example |          |      |                    |                        | dataset  |                  |                                                     |                                      
        | wsdl_res |      |                    |                        | wsdl     |                  | https://ws.registrucentras.lt/broker/index.php?wsdl |                                      
        | res1     |      |                    |                        | soap     |                  | Get.GetPort.GetPortType.GetData                     | wsdl(wsdl_res)                                     
        |          |      | GetData            |                        |          |                  | /                                                   |                                      
        |          |      |                    |                        | param    | type             | input/ActionType                                    | input()                              
        |          |      |                    |                        | param    | caller           | input/CallerCode                                    | creds("caller").input()              
        |          |      |                    |                        | param    | user             | input/EndUserInfo                                   | creds("user").input()                
        |          |      |                    |                        | param    | params           | input/Parameters                                    | input("foo")                              
        |          |      |                    |                        | param    | time             | input/Time                                          | input()                              
        |          |      |                    |                        | param    | signature        | input/Signature                                     | creds("signature").input()           
        |          |      |                    |                        | param    | caller_signature | input/CallerSignature                               | creds("caller_signature").input()    
        |          |      |                    | type                   | string   |                  |                                                     | param("type")
        |          |      |                    | params                 | string   |                  |                                                     | param("params")
        |          |      |                    | time                   | string   |                  |                                                     | param("time")
        |          |      |                    | code                   | integer  |                  | ResponseCode                                        |                                     
        |          |      |                    | data                   | string   |                  | ResponseData                                        |                                      
```
DSA aprašyta nauja `prepare` funkcija:
* `def creds(source)` - funkcija nurodo, kad šio `resource.param` reikšmė bus skaitoma iš Oauth2 `access_token.client_id`. Pagal `client_id` randamas `.yml` failas, kuriame saugomi su client susieti credentials. Pa `source` stulpelis nurodo credentials atributo pavadinimą, `ref` stulpelis nurodo pavadinimą, kurį naudos Spinta (`input()` funkcijoje). 
  * Kiekvienas `resource.param` taip pat turi būti aprašytas ir kaip `type=property`.
  * Naudojant funkcijas `creds().input()` kartu reiškia, kad parametras bus skaitomas iš Oauth2 credentials ir naudojamas SOAP request'e. Spinta abi funkcijas interpretuos kaip: `.input(creds())`.

### Spinta URL:
```
spinta_url/example/GetData/?type="46"&time="2024-05-06"
```

### Python request kodas:
```python
from zeep import Client

zeep_client = Client("wsdl-url")
zeep_client.service.GetData(
    input={
        "ActionType": 46,                               # from URL
        "CallerCode": "some info",                      # from credentials file
        "EndUserInfo": "some more info",                # from credentials file
        "Parameters": "foo",                            # from `input(...)` default
        "Time": "2024-05-06",                           # from URL
        "Signature": "4t4fs34",                         # from credentials file
        "CallerSignature": "654rfni5t"                  # from credentials file
    }
)
```

Spinta rezultatas. **Pastaba: `resource.param` turintys `creds()` funkciją rezultate nerodomi**:
```json
{
    "_data": [
        {
            "_revision": null,
            "_type": "example/JuridinisAsmuo",
            "_base": null,
            "type": 46,
            "params": "foo",
            "time": "2024-05-06",
            "code": 10,
            "data": "some response data"
        }
    ]
}
```
