### ISSUE TITLE
Aiškesnis klaidos pranešimas neradus user function

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#1335]
Dabar tarkim turint tokią formulę:

```python
extract("zip")["pk_dalyviai.csv"].file(encoding: "cp1257").tabular(sep: ";")
```

Gaunamas toks klaidos pranešimas, nes nėra įgyvendinta `file` funkcija:

```
NotImplementedError: Could not find signature for file: <LinkBuilder, MethodExpr>
```

Reikėtu rodyti aiškesnį klaidos pranešimą, pridedant kontekstą, kokia savybė ar modelis turi formulę, kurioje yra klaidą. Klaidos pranešimas galėtu atrodyti taip:

```
NotImplementedError:
  Could not find user function signature `file(LinkBuilder, MethodExpr)` for
  `extract("zip")["pk_dalyviai.csv"].file(encoding: "cp1257").tabular(sep: ";")` formula.
Context:
  component: spinta.components.Resource
  manifest: default
  schema: sdsa_5:75
  dataset: datasets/gov/rc/ar/adresai
  resource: ar
  model: datasets/gov/rc/ar/adresai/Adresas
  entity: adr_adresas_vw
  resource.backend: mydb
```

## Susiję

- https://github.com/atviriduomenys/spinta/issues/987
- https://github.com/atviriduomenys/spinta/issues/1078
- https://github.com/atviriduomenys/spinta/issues/1196
