### ISSUE TITLE
Do not use _id as dataset object identifier

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#31]
Currently in datasets `_id` is used to identify same object, by hashing several fields that uniquely identify an object. This identifier is sha1, generated from a list of values serialized with msgpack.

Maybe, instead of using `_id` for that, we could simply list all the fields, that uniquely identifies this object, then on UPSERT operation, these values could be passed to `_where`.

Benefits:

- `_id` no longer needs to be sha1, and can be uuid.
- No need to use internal `_id` field in yaml files, `_id` will be autogenerated.
- This list of fields can be reused later when merging dataset data to canonical models.

Example how this could look:

```yaml
type: dataset
resources:
  resource:
    objects:
      origin:
        model:
          identifier:
            - id
          properties:
            id:
              type: integer
              source: ID
```

All properties used as identifiers must bu listed as model properties and must have a source. Without source, we can't identify an object.
