### ISSUE TITLE
Possibility to call a python function to transform and validate dataset value

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#38]
Add possibility to call a Python function, on dataset model or property, this function would do validation and value transformation.

Values can be transformed at model level, like this:

```yaml
type: dataset
resources:
  resource:
    objects:
      origin:
        model:
          prepare:
            id:
              - split(this.OFFICIAL_ID, ",")[0].strip()
              - check(len(this) = 9, "Invalid company registration number.")
              - check(this.re("\d+"))
          properties:
            id:
              type: integer
              source: id
```

Or at property level, like this:

```yaml
type: dataset
resources:
  resource:
    objects:
      origin:
        model:
          properties:
            id:
              type: integer
              source: OFFICIAL_ID
              prepare:
                - split(this, ",")[0].strip()
                - check(len(this) = 9, "Invalid company registration number.")
                - check(this.re("\d+"))
```

All functions must be registered in configuration.

Same function can do different things, depending on given argument types (multipledispatch).

All `prepare` statements should be RQL strings.

`this` always points to a current value, but instead of this an original field name can be used.

When there is a list of `prepare` statements, each statement must return final prepared value, which will be assed to the next statement. In case of comparison operators, they also must compared value or throw an error.

When we need to check multiple things, then we can use `oneof`:

```
oneof(
  PARAM1,
  PARAM2
)
```

All spaces and new lines are completely ignored. If you need a space, you need to use `\ `, for new lines it would be `\n`.

User defined functions must come from a namespace, for example:

```
vpt.regno(OFFICIAL_ID)
```

All namespaces must be registered in configuration. A namespace is a python module, where all functions are registered like this:

```python
@ufunc.register()
def regno(value: str) -> str:
    ...
```

In configuration function registration looks like this:

```python
config = {
    'ufuncs': {
        '': [
            'spinta.commands.ufuncs',
        ],
        'vpt': [
            'lodam.ufuncs.vpt',
        ],
    }
}
```

**Corner cases**:

- RQL should be escaped with % based URL escapes, but these are not readable, for exapmle in order to escape `,` it would be `'Reference to deleted milestone 2'C`. So I think `\,` looks more readable.
- What if source has a property named `this`? Then source value takes priority. In order to get current value `this()` must be used.

Links:

- https://github.com/sirex/databot-bots/blob/master/bots/lrs/seimonariai.py

# Ideas

## Arguments as yaml arrays

There can be large number of arguments for some operators, for example:

```yaml
prepare:
  - |
    oneof(
      PARAM1,
      oneof(
        PARAM2,
        PARAM3
      ),
      ...
    )
```

Same thing could be rewritten like this:

```yaml
prepare:
  - oneof():
    - PARAM1
    - oneof():
      - PARAM2
      - PARAM3
    - ...
```

## Definding ufuncs

```python
@ufunc(Context, DataType)
def check(context, dtype, this, value, message, **kwargs):
    if bool(value) is False:
        raise ValidationError(message.format(**kwargs))
    return this[-1]

@ufunc(Context, DataType)
def len(context, dtype, this, value):
    return len(value)
```

All ufuncts are multipli dispatch functions. `context`, `dtype` and `this` is always passed by the engine and all other arguments are passed by the user. `this` is a list indicating all values in call stack. `this[0]` always points to model data, `this[-1]` always points to latest value.

### Delayed argument interpretation

Sometimes you want to delay argument interpretation, you can do that, by annotating value type, like this:

```python
@ufunc(Context)
def if_(context, dtype, this, value, then: ParseTree, else_: ParseTree):
    if value:
        return execute(then)
    else:
        return execute(else_)
```

With this ufunc, you can do `if(this > 42, call1(), call2())`. Here first argument will be resolved automatically, but arguments `then` and `else_` will be passed as parse trees and `if_` function will be responsible for executing them if needed.

## Ufunc with reserved python names

If you need to define an ufunc with reserved python name, you can add `_` suffix, it will be stripped automatically. For example `if_` becomes `if`.
