### ISSUE TITLE
Pull only changed data

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#42]
Currently all source data is read every time. It would be much more efficient if only new changes would be pulled. This would be possible if source has a change identifier, like timestamp when data was updated or another monotonically incrementing value, that would identify when value has changed.

In manifest this could look like this:

```yaml
source: some_table
revision: revision
properties:
  revision:
    type: datetime
    source: last_update_time
```

Here `revision` would take a property name, with monotonically incrementing revision numbers.

Last accessed revision would be stored on a default backend and all subsequent pulls would take only new data since last seen revision.

### Related

- https://github.com/atviriduomenys/spinta/issues/366
