### ISSUE TITLE
Custom backend configuration for models

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#599]
Add possibility to configure models with a custom backend options. This could be used for things like moving some tables to hypertable or changing column types like `integer` to `bigint` (#462).

Configuration could looks like this `config.yaml`:

```yaml
backends:
  mybackend:
    type: postgresql
    dsn: postgresql://...

models:
  datasets/gov/example/MyModel:
    backend: mybackend  # specify which backend to use for storing data
    option: value  # add custom, backend specific options for model
    properties:
      my_prop:
        backend: mybackend  # optionally store data in a different backend,
                            # applies for some property types like file type
        option: value  # add custom, backend specific options for property
```

When running `spinta migrate`, custom backend specific options must be respected.

For `properties` following options could be added:

- `type` - a custom backend specific type, liek `bigint`, instead of using default `integer`, this override should be used instead.

Example how `type` overrides could be implemented:

```yaml
models:
  datasets/gov/example/City:
    properties:
      population:
        type: sqlalchemy.types.BigInteger
      history:
        type:
          name: sqlalchemy.types.String
          lenght: 200
```

If `type` is `string`, then specified type class is imported and initialized, if `type` is an object, then `name` is used as path to class and other attributes as keyword arguments to class.

Direct backend assignment to a model is done here:

https://github.com/atviriduomenys/spinta/blob/a0c084b7f03ebc8159fb806a412622a7ad9ca2ba/spinta/types/model.py#L181-L185

### Related

- https://github.com/ivpk/dsa/issues/88
- https://github.com/atviriduomenys/spinta/issues/462
- https://github.com/atviriduomenys/spinta/issues/172
