### ISSUE TITLE
Move dataset models to separate YAML files

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#61]
Some datasets can be really huge, they can contains thousands of properties and on top of that, same YAML files contains schema changes, so YAML files can grow really big. Now there is a file with about 30,000 lines already.

To make YAML file sizes manageable, each dataset model should be stored in separate YAML file. Datastes should also be stored in separate YAML files.

For example, here is how a separate dataset file could look:

```yaml
# datasets/gov/vpt/old.dataset.yml
type: dataset
name: gov/vpt/old
resources:
  mssql:
    type: sql
```

And a model from that dataset:

```yaml
# datasets/gov/vpt/old/reports.yml
type: model
name: gov/vpt/old/reports
dataset: gov/vpt/old
resource: mssql
source: REPORTS
properties:
  _id:
    type: pk
    source: REPORT_ID
```

Then inventorying tables could look like this:

| dataset     | resource | extends | model  | property | source             | type | ref | level | state | title | description |
| ----------- | -------- | ------- | ------ | -------- | ------------------ | ---- | --- | ----- | ----- | ----- | ----------- |
| gov/vpt/old |          |         |        |          |                    |      |     |       |       |       |             |
|             | mssql    |         |        |          |                    |      |     |       |       |       |             |
|             |          | none    |        |          |                    |      |     |       |       |       |             |
|             |          |         | report |          | REPORTS[STATUS=1]  |      |     |       |       |       |             |
|             |          |         |        | _id      | REPORT_ID          | pk   |     | 4     | open  |       |             |

In order to join serveral sources into one model `base` property should be used, like this:

```yaml
# datasets/gov/dc/administracija.dataset.yml
type: dataset
name: gov/dc/administracija
resources:
  sql:
    type: sql
```

```yaml
# datasets/gov/dc/administracija.yml
type: model
name: gov/dc/administracija
dataset: gov/dc/administracija
resource: sql
properties:
  priklauso:
    type: ref
    object: gov/dc/administracija
  lygis:
    type: integer
  pavadinimas:
    type: string
```

```yaml
# datasets/gov/dc/administracija/apskritis.yml
type: model
name: gov/dc/administracija/apskritis
dataset: gov/dc/administracija
resource: sql
source: APSKRITYS
extends:
  model: gov/dc/administracija
  using: _id
  proxy: true
properties:
  _id:
    type: pk
    source: id
  priklauso:
    type: ref
    object: gov/dc/administracija
  lygis:
    type: integer
    prepare: 1
  pavadinimas:
    type: string
    source: pavadinimas
```

```yaml
# datasets/gov/dc/administracija/savivaldybe.yml
type: model
name: gov/dc/administracija/savivaldybe
dataset: gov/dc/administracija
resource: sql
source: SAVIVALDYBES
extends:
  model: gov/dc/administracija
  using: _id
  proxy: true
properties:
  _id:
    type: pk
    source: id
  priklauso:
    type: ref
    object: gov/dc/administracija
    source: apskritis
  lygis:
    type: integer
    prepare: 2
  pavadinimas:
    type: string
    source: pavadinimas
```

Inventorying table will look like this:

| dataset               | resource | extends               | model                      | property    | source       | type    | ref                   | level | state | title | description |
| --------------------- | -------- | --------------------- | -------------------------- | ---------   | ------------ | ----    | --------------------- | ----- | ----- | ----- | ----------- |
| gov/dc/administracija |          |                       |                            |             |              |         |                       |       |       |       |             |
|                       | sql      |                       |                            |             |              |         |                       |       |       |       |             |
|                       |          | none                  |                            |             |              |         |                       |       |       |       |             |
|                       |          |                       | administracija             |             |              |         |                       |       |       |       |             |
|                       |          |                       |                            | priklauso   |              | ref     | gov/dc/administracija | 4     | open  |       |             |
|                       |          |                       |                            | lygis       |              | integer |                       | 4     | open  |       |             |
|                       |          |                       |                            | pavadinimas |              | string  |                       | 4     | open  |       |             |
|                       |          | gov/dc/administracija |                            |             |              |         |                       |       |       |       |             |
|                       |          |                       | administracija/apskritis   |             | APSKRITYS    |         |                       |       |       |       |             |
|                       |          |                       |                            | _id         | id           | pk      |                       | 4     | open  |       |             |
|                       |          |                       |                            | priklauso   |              | ref     | gov/dc/administracija | 4     | open  |       |             |
|                       |          |                       |                            | lygis       | 1            | integer |                       | 4     | open  |       |             |
|                       |          |                       |                            | pavadinimas | pavadinimas  | string  |                       | 4     | open  |       |             |
|                       |          | gov/dc/administracija |                            |             |              |         |                       |       |       |       |             |
|                       |          |                       | administracija/savivaldybe |             | SAVIVALDYBES |         |                       |       |       |       |             |
|                       |          |                       |                            | _id         | id           | pk      |                       | 4     | open  |       |             |
|                       |          |                       |                            | priklauso   | apskritis    | ref     | gov/dc/administracija | 4     | open  |       |             |
|                       |          |                       |                            | lygis       | 2            | integer |                       | 4     | open  |       |             |
|                       |          |                       |                            | pavadinimas | pavadinimas  | string  |                       | 4     | open  |       |             |
