### ISSUE TITLE
Define backends in manifest

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#80]
Currently backends can be defined in configuration like this:

```yaml
backends:
  default:
    type: postgresql
    dsn: postgresql://host/db
```

Also, there is additional option to override backend for specific dataset resources in manifest like this:

```yaml
datasets:
  default:                      # manifest
    gov/ivpk/adp:               # dataset
      db: postgresql://host/db  # resource
```

I don't like this type of backend configuration. And I think it should be removed.

The new and better way to specify backends is in manifest files, for example:

```yaml
backends:
    type: postgresql
    dsn: postgresql://host/db
```

Or in tabular format:

resource | type   | ref     | source |
------   | ------ | ------- | ------ |
default  | sql    |         | postgresql://host/db |
