### ISSUE TITLE
Support hosting multiple domains

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#84]
Add possibility to host multiple domains on a single server instance. With an option, to serve only specified namespaces.

For example server A, would serve all datasets, but server B would serve only `/datasets/gov/B`.

In configuration files, this could look like this:

```yaml
hosts:
  a.example.com:
    # Root is not specified, that means, serve everything.
  b.example.com:
    root: datasets/gov/B
```

On URL routing, domain name would be checked against configured `hosts` and if some host has a root, then automatically add given root.

But also, I would have to remove root prefix, when formatting URLs and also change model type. But maybe model type should stay unchanged, only url without prefix could be accepted?
