### ISSUE TITLE
Fix sourceparams in docs

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#97]
In [documentation](https://atviriduomenys.readthedocs.io/lt/latest/sources.html) `sourceparams` parameter is used, but it is not actually implemented. Source parameters are defined like that:

```yaml
source:
  name: mydata
  param: value
```

If there are no source params, then same thing could look like this:

```yaml
source: mydata
```
